name: lint (pre-commit)

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"  
  push:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: v1.20.x
    - name: Install dependencies
      run: |
        cd /tmp && go install github.com/go-critic/go-critic/cmd/gocritic@latest
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install golang.org/x/lint/golint@latest
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with: 
        extra_args: --all-files
